import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/ui/footer";
import Navbar from "./components/ui/navbar";
import { Noto_Sans_Cherokee } from 'next/font/google'
import { Lexend } from 'next/font/google'



export const noto_sans_cherokee = Noto_Sans_Cherokee({
  subsets : ['latin'],
  display : 'swap'
})

export const lexend =  Lexend({
  subsets : ['latin'],
  display : 'swap'
})  


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
         className={`${lexend.className} `}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
